"""Add description column to Todo table

Revision ID: 02da6aae563d
Revises: 
Create Date: 2023-11-01 11:22:19.960857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02da6aae563d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
